//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWPetrovskogo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ApplicationID { get; set; }
        public string TransferName { get; set; }
        public int CompanyID { get; set; }
        public string Reason { get; set; }
        public int ArticleID { get; set; }
        public decimal SumInRubles { get; set; }
        public int StatusID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Company Company { get; set; }
        public virtual Status Status { get; set; }
    }
}
