//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWPetrovskogo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public int BudgetID { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int ArticleID { get; set; }
        public decimal Limit { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
